default: gemini

openai:
  provider: openai
  model_name: gpt-5-nano

huggingface:
  provider: huggingface
  model_name: meta-llama/Llama-3.1-8B-Instruct

gemini:
  provider: gemini
  model_name: gemini-2.5-flash-lite
